apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: registry.cube.local:5000/podoi-website
  newTag: 1.0.0
