apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blog-postgres-pvc
  namespace: podoi
  labels:
    app: blog-postgres
    recurring-job.longhorn.io/source: enabled
    recurring-job-group.longhorn.io/backup-postgres: enabled
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
